In [ ]:
import numpy as np

In [ ]:
arr = np.array(45)

In [ ]:
arr.ndim

0

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr.ndim

1

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr.ndim

2

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],
               [[9,8,7],[6,5,4]]])

In [ ]:
arr[0][1][1]

5

In [ ]:
arr.ndim

3

In [ ]:
[4,2,3,1][2]

3

In [ ]:
Ii = [4,2,[3,5,1,1]]

In [ ]:
Ii[2][1]

5

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[0][1]

2

OR

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
arr[-1]

array([4, 5, 6])

In [ ]:
arr[0,1]

2

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[-1]

array([4, 5, 6])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[:,0]

array([1, 4])

In [ ]:
arr[:,-1]

array([3, 6])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

assigning

In [ ]:
arr[0,2] = 100

In [ ]:
arr

array([[  1,   2, 100],
       [  4,   5,   6]])

In [ ]:
a = np.array([[[[[1,2,3],[4,5,6]],[[9,8,7],[6,5,4]]]]])
print(a)

[[[[[1 2 3]
    [4 5 6]]

   [[9 8 7]
    [6 5 4]]]]]


In [ ]:
a = np.array([[2,5,1], [2,9,5], [9,4,1]])
print(a)

[[2 5 1]
 [2 9 5]
 [9 4 1]]


In [ ]:
a[:,1]

array([5, 9, 4])

In [ ]:
a[1:3,0:2]

array([[2, 9],
       [9, 4]])

In [ ]:
a[0:5:2,0:5:2]

array([[2, 1],
       [9, 1]])

In [ ]:
a[0:2,1:3]

array([[5, 1],
       [9, 5]])

In [ ]:
a = np.array([[2,5,1,4,3], [2,9,5,2,1], [9,4,1,2,4],[1,1,6,9,5]])
print(a)

[[2 5 1 4 3]
 [2 9 5 2 1]
 [9 4 1 2 4]
 [1 1 6 9 5]]


In [ ]:
a[0:5:2,0:5:2]

array([[2, 1, 3],
       [9, 1, 4]])

In [ ]:
a

array([[2, 5, 1, 4, 3],
       [2, 9, 5, 2, 1],
       [9, 4, 1, 2, 4],
       [1, 1, 6, 9, 5]])

In [ ]:
a[2,3] = 100

In [ ]:
a

array([[  2,   5,   1,   4,   3],
       [  2,   9,   5,   2,   1],
       [  9,   4,   1, 100,   4],
       [  1,   1,   6,   9,   5]])

In [ ]:
a[2,1:4] = [33,35,36]

In [ ]:
a

array([[ 2,  5,  1,  4,  3],
       [ 2,  9,  5,  2,  1],
       [ 9, 33, 35, 36,  4],
       [ 1,  1,  6,  9,  5]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(4, 5)

In [ ]:
a.size

20

In [ ]:
b =np.array([0,0,0,0,1,0,0,0])

In [ ]:
b

array([0, 0, 0, 0, 1, 0, 0, 0])

In [ ]:
b.shape

(8,)

In [ ]:
b.size

8

In [ ]:
b.reshape(4,2)

array([[0, 0],
       [0, 0],
       [1, 0],
       [0, 0]])

In [ ]:
b.reshape(2,4)

array([[0, 0, 0, 0],
       [1, 0, 0, 0]])

In [ ]:
b.reshape(8,1)

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [ ]:
b.reshape(1,8)

array([[0, 0, 0, 0, 1, 0, 0, 0]])

In [ ]:
a

array([[ 2,  5,  1,  4,  3],
       [ 2,  9,  5,  2,  1],
       [ 9, 33, 35, 36,  4],
       [ 1,  1,  6,  9,  5]])

In [ ]:
a.shape

(4, 5)

In [ ]:
a.size

20

In [ ]:
a.reshape(2,10)

array([[ 2,  5,  1,  4,  3,  2,  9,  5,  2,  1],
       [ 9, 33, 35, 36,  4,  1,  1,  6,  9,  5]])

In [ ]:
a.reshape(2,1,2,5)

array([[[[ 2,  5,  1,  4,  3],
         [ 2,  9,  5,  2,  1]]],


       [[[ 9, 33, 35, 36,  4],
         [ 1,  1,  6,  9,  5]]]])

In [ ]:
a.reshape(2,2,5)

array([[[ 2,  5,  1,  4,  3],
        [ 2,  9,  5,  2,  1]],

       [[ 9, 33, 35, 36,  4],
        [ 1,  1,  6,  9,  5]]])

In [ ]:
a.reshape(1,2,2,5)

array([[[[ 2,  5,  1,  4,  3],
         [ 2,  9,  5,  2,  1]],

        [[ 9, 33, 35, 36,  4],
         [ 1,  1,  6,  9,  5]]]])

In [ ]:
array_1D = np.array([10,11,12,13, 14])
print("First element of array_1D:", array_1D[0])
# Using negative indices to display the last element of each array
print("Last element of array_1D:", array_1D[-1])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
print("First element of array_2D:", array_2D[0, 0])
# Using negative indices to display the last element of each array
print("Last element of array_2D:", array_2D[-1, -1])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,55]]])
print("First element of array_3D:", array_3D[0, 0, 0])
# Using negative indices to display the last element of each array
print("Last element of array_3D:", array_3D[-1, -1, -1])

First element of array_1D: 10
Last element of array_1D: 14
First element of array_2D: 20
Last element of array_2D: 55
First element of array_3D: 1
Last element of array_3D: 55


Element wise

In [ ]:
a = np.array([[1,2,3,4,5],[3,2,1,2,5]])
a

array([[1, 2, 3, 4, 5],
       [3, 2, 1, 2, 5]])

In [ ]:
b = np.array([[5,3,1,4,5],[3,3,2,1,5]])
b

array([[5, 3, 1, 4, 5],
       [3, 3, 2, 1, 5]])

In [ ]:
a + b

array([[ 6,  5,  4,  8, 10],
       [ 6,  5,  3,  3, 10]])

In [ ]:
np.add(a,b)

array([[ 6,  5,  4,  8, 10],
       [ 6,  5,  3,  3, 10]])

In [ ]:
np.multiply(a,b)

array([[ 5,  6,  3, 16, 25],
       [ 9,  6,  2,  2, 25]])

In [ ]:
np.divide(a,b)

array([[0.2       , 0.66666667, 3.        , 1.        , 1.        ],
       [1.        , 0.66666667, 0.5       , 2.        , 1.        ]])

In [ ]:
b = b.reshape(5,2)

In [ ]:
b

array([[5, 3],
       [1, 4],
       [5, 3],
       [3, 2],
       [1, 5]])

In [ ]:
a

array([[1, 2, 3, 4, 5],
       [3, 2, 1, 2, 5]])

In [ ]:
np.matmul(a,b)

array([[39, 53],
       [33, 49]])

In [ ]:
array_1D = np.array([10,11,12,13, 14])
array_1D_copy = np.copy(array_1D)
array_1D_copy += 2
print("array_1D_copy after adding 2 to every element:", array_1D_copy)
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D_copy = np.copy(array_2D)
array_2D_copy += 2
array_2D_copy *= 100
print("array_2D_copy after multiplying by 100:", array_2D_copy)
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,55]]])
array_3D_copy = np.copy(array_3D)
array_3D_copy += 2
array_3D_copy += 1000
print("array_3D_copy after adding 1000 to every element:", array_3D_copy)

array_1D_copy after adding 2 to every element: [12 13 14 15 16]
array_2D_copy after multiplying by 100: [[2200 3200 4200 5200 6200]
 [4500 5600 6700 7800 8900]
 [1300 2400 3500 4600 5700]]
array_3D_copy after adding 1000 to every element: [[[1003 1004 1005 1006 1007]
  [1013 1023 1033 1043 1053]]

 [[1013 1014 1015 1016 1017]
  [1053 1054 1055 1056 1057]]]


In [ ]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [ ]:
array_2D + 2

array([[22, 32, 42, 52, 62],
       [45, 56, 67, 78, 89],
       [13, 24, 35, 46, 57]])

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float32)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = float)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [ ]:
array_a = np.array([[1,-4,3],[0,5,6]], dtype = bool)
array_a

array([[ True,  True,  True],
       [False,  True,  True]])

In [ ]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = str)
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [ ]:
# Redefine array_1D as NumPy strings
array_1D = np.array(['10','11','12','13','14'], dtype=str)
print("array_1D with dtype np.str:", array_1D)
# Redefine array_2D as Complex Numbers
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype=complex)
print("array_2D with dtype np.complex:", array_2D)
# Redefine array_3D as 64-bit Floats
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype=np.float64)
print("array_3D with dtype np.float64:", array_3D)

array_1D with dtype np.str: ['10' '11' '12' '13' '14']
array_2D with dtype np.complex: [[20.+0.j 30.+0.j 40.+0.j 50.+0.j 60.+0.j]
 [43.+0.j 54.+0.j 65.+0.j 76.+0.j 87.+0.j]
 [11.+0.j 22.+0.j 33.+0.j 44.+0.j 55.+0.j]]
array_3D with dtype np.float64: [[[ 1.  2.  3.  4.  5.]
  [11. 21. 31. 41. 51.]]

 [[11. 12. 13. 14. 15.]
  [51. 52. 53. 54.  5.]]]


In [ ]:
first_column = array_2D[:, 0]

In [ ]:
last_two_columns_second_row = array_2D[1, -2:]

In [ ]:
second_row_excluding_last_two_columns = array_2D[1, :-2]

In [ ]:
array_1D = np.array([10, 11, 12, 13, 14])
array_2D = np.array([[20, 30, 40, 50, 60], [43, 54, 65, 76, 87], [11, 22, 33, 44, 55]])
array_3D = np.array([[[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]], [[11, 12, 13, 14, 15], [51, 52, 53, 54, 5]]])

first_column = array_2D[:, 0]
last_two_columns_second_row = array_2D[1, -2:]
second_row_excluding_last_two_columns = array_2D[1, :-2]

print("First column of the 2-D array:", first_column)
print("Last two columns of the 2nd row of the 2-D array:", last_two_columns_second_row)
print("2nd row of the 2-D array excluding the last two columns:", second_row_excluding_last_two_columns)

First column of the 2-D array: [20 43 11]
Last two columns of the 2nd row of the 2-D array: [76 87]
2nd row of the 2-D array excluding the last two columns: [43 54 65]


In [ ]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
array_0s = np.zeros(3)
array_0s

array([0., 0., 0.])

In [ ]:
array_0s = np.zeros((3,2,3))
array_0s

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
array_0s = np.zeros(3)
array_0s

array([0., 0., 0.])

In [ ]:
array_0s = np.zeros(shape = (2,3), dtype = np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [ ]:
array_1s = np.ones(shape  = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_1s = np.ones(6)
array_1s

array([1., 1., 1., 1., 1., 1.])

In [ ]:
array_1s = np.ones(shape  = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_1s * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
array_10s = np.ones(shape  = (2,3)) * 10
array_10s

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
array_full = np.full(shape = (2,3), fill_value = 10)
array_full

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
array_full = np.full(shape = (2,3), fill_value = 'Three-Six-Five')
array_full

array([['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five'],
       ['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five']],
      dtype='<U14')

In [ ]:
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [ ]:
array_empty_like = np.empty_like(matrix_A)
array_empty_like

array([[4626322717216342016, 4629137466983448576, 4630826316843712512,
        4632233691727265792, 4633641066610819072],
       [4631248529308778496, 4632796641680687104, 4634274385308418048,
        4635048441494372352, 4635822497680326656],
       [4622382067542392832, 4626885667169763328, 4629841154425225216,
        4631389266797133824, 4632937379169042432]])

In [ ]:
array_empty_like = np.empty_like(matrix_A, dtype = bool)
array_empty_like

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
array_0s_like = np.zeros_like(matrix_A)
print(array_0s_like)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
array_0s_like = np.ones_like(matrix_A) * 15
print(array_0s_like)

[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]


In [ ]:
array_rng = np.arange(0,30,2.5,dtype = int)

In [ ]:
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
# Arrays of size 10
array_empty = np.empty(10)
array_zeros = np.zeros(10)
array_ones = np.ones(10)
array_twos = np.full(10, 2)

# Arrays of size 2 by 4
array_empty_2d = np.empty((2, 4))
array_zeros_2d = np.zeros((2, 4))
array_ones_2d = np.ones((2, 4))
array_twos_2d = np.full((2, 4), 2)

print("Array Empty:", array_empty)
print("Array Zeros:", array_zeros)
print("Array Ones:", array_ones)
print("Array Twos:", array_twos)

print("\nArray Empty 2D:")
print(array_empty_2d)

print("\nArray Zeros 2D:")
print(array_zeros_2d)

print("\nArray Ones 2D:")
print(array_ones_2d)

print("\nArray Twos 2D:")
print(array_twos_2d)

Array Empty: [0.2        0.66666667 3.         1.         1.         1.
 0.66666667 0.5        2.         1.        ]
Array Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array Twos: [2 2 2 2 2 2 2 2 2 2]

Array Empty 2D:
[[4.73361403e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

Array Zeros 2D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array Ones 2D:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array Twos 2D:
[[2 2 2 2]
 [2 2 2 2]]


In [ ]:
# Arrays of size 10
array_empty = np.empty(10)
array_zeros = np.zeros(10)
array_ones = np.ones(10)
array_twos = np.full(10, 2)

In [ ]:
array_empty

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

You don't have twos, threes in numpy what you have to do is to divide the number with the number you want it to be.

In [ ]:
array_twos

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Arrays of size 2 by 4
array_empty_2d = np.empty((2, 4))
array_zeros_2d = np.zeros((2, 4))
array_ones_2d = np.ones((2, 4))
array_twos_2d = np.full((2, 4), 2)

In [ ]:
array_empty_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array_zeros_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
array_ones_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
array_twos_2d

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

np.eye creates diagonal for you

In [ ]:
np.eye(10) * 8

array([[8., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 8., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 8., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 8., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 8., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 8., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 8.]])

In [ ]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

to give you the size you add .size

In [ ]:
np.arange(0,30,2).size

15

to reshape it you add .reshape at the end of the code.

Then you add want to reshape it with.

In [ ]:
np.arange(0,30,2).reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

Statistical function

In [ ]:
x = np.array([1, 2, 9,5, 4, 5])
np.mean(x)

4.333333333333333

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

np.mean(x, axis=1)

array([2., 5.])

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

np.mean(x, axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.median(x, axis=1)

array([2., 5., 8.])

How to check minimum for each column

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.min(x,axis = 0)

array([1, 2, 3])

How to check minimum for each row

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.min(x,axis = 1)

array([1, 4, 7])

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.max(x,axis = 0)

array([7, 8, 9])

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

np.max(x,axis = 1)

array([3, 6, 9])

Amax is another way is writiung max
but it always need axis for it work

In [ ]:
np.amax(x,axis = 1)

array([3, 6, 9])

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

this means anything equal to less than 3 you should assign it with 3

In [ ]:
np.minimum(x,3)

array([[1, 2, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
x = np.array([[1, 2, 3],
              [41, 9, 6],
              [7, 0, 9]])

y = np.array([[11, 2, 3],
              [4, 5, 61],
              [72, 8, 9]])

In [ ]:
np.minimum(x,y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [ ]:
np.maximum(x,y)

array([[11,  2,  3],
       [41,  9, 61],
       [72,  8,  9]])

In [ ]:
x > y

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [ ]:
result = np.empty_like(x)
for col in range(3):
  for row in range(3):
    if y[col][row] < x[col][row]:
      result[col][row] = x[col][row]

    elif y[col][row] > x[col][row]:
      result[col][row] = y[col][row]

print(result)

[[11  0  0]
 [41  9 61]
 [72  8  0]]


In [ ]:
x

array([[ 1,  2,  3],
       [41,  9,  6],
       [ 7,  0,  9]])

In [ ]:
np.minimum.reduce(x)

array([1, 0, 3])

In [ ]:
x

array([[ 1,  2,  3],
       [41,  9,  6],
       [ 7,  0,  9]])

In [ ]:
np.average(x,axis = 1)

array([ 2.        , 18.66666667,  5.33333333])

In [ ]:
np.average(x,axis = 1,weights = [2,7,2])

array([ 2.        , 14.27272727,  2.90909091])

In [ ]:
x

array([[ 1,  2,  3],
       [41,  9,  6],
       [ 7,  0,  9]])

In [ ]:
np.var(x)

140.66666666666666

In [ ]:
np.std(x)

11.86029791643813

Covariance and correlation :

Covariance is relationship between the variances

In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A : \n",cov_matrix)

Covariance matrix of matrix_A : 
 [[ 1.5 -2.   2. ]
 [-2.   7.7 -7. ]
 [ 2.  -7.   8.5]]


In [ ]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [ ]:
matrix_A = np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
corr_matrix = np.corrcoef(matrix_A)
print("Correlation matrix of matrix_A : \n",corr_matrix)

Correlation matrix of matrix_A : 
 [[ 1.         -0.58848989  0.56011203]
 [-0.58848989  1.         -0.8652532 ]
 [ 0.56011203 -0.8652532   1.        ]]


In [ ]:
np.array([[1,2,3],[3,np.nan,5]])

array([[ 1.,  2.,  3.],
       [ 3., nan,  5.]])

linspace
creation of number from 0 to 2


In [ ]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
np.zeros(2)

array([0., 0.])

the double bracket increases the squre bracket

In [ ]:
np.zeros((1,2))

array([[0., 0.]])

Note random is decimal while randit is whole number

In [ ]:
np.random.random((5,5))

array([[0.53694335, 0.457907  , 0.77511223, 0.47498979, 0.63205172],
       [0.09754359, 0.10610674, 0.30867863, 0.75862388, 0.14018221],
       [0.87336005, 0.04014638, 0.20967808, 0.54348458, 0.26194844],
       [0.89571792, 0.50032773, 0.96151698, 0.22545985, 0.25041913],
       [0.56493497, 0.08759706, 0.4015162 , 0.69509134, 0.89342927]])

In [ ]:
np.random.randint((2,6),9)

array([7, 7])

Its guesing the numbers from 0 to 10

In [ ]:
np.random.randint(0,10,size = (2,4))

array([[8, 8, 7, 6],
       [0, 0, 7, 8]])

Its guessing numbers from 2 to 4

In [ ]:
np.random.randint(2,4)

2

In [ ]:
import numpy as np
grades =  np.array([85, 75, 98, 89, 83])

In [ ]:
grades.astype(float)

array([85., 75., 98., 89., 83.])

In [ ]:
grades.astype(str)

array(['85', '75', '98', '89', '83'], dtype='<U21')

In [ ]:
type(grades)

numpy.ndarray

In [ ]:
grades

array([85, 75, 98, 89, 83])

In [ ]:
np.append(grades, 66)

array([85, 75, 98, 89, 83, 66])

If you want to insert a number at centre of variable you can specify the location you want to add the number between the variables you already created

In [ ]:
np.insert(grades, 2, [0,90])

array([85, 75,  0, 90, 98, 89, 83])

In [ ]:
np.resize(grades, (2,3))

array([[85, 75, 98],
       [89, 83, 85]])

In [ ]:
np.size

<function size at 0x7b77305ea1b0>

In [ ]:
np.delete(grades,1)

array([85, 98, 89, 83])

In [ ]:
grades

array([85, 75, 98, 89, 83])

In [ ]:
x = np.array([[3,1,1],[15,3,6]])
y = np.array([[5,2,1], [4,23,1]])

In [ ]:
np.concatenate((x,y),axis = 0)

array([[ 3,  1,  1],
       [15,  3,  6],
       [ 5,  2,  1],
       [ 4, 23,  1]])

In [ ]:
np.concatenate((x,y),axis = 1)

array([[ 3,  1,  1,  5,  2,  1],
       [15,  3,  6,  4, 23,  1]])

In [ ]:
ii = np.concatenate((x,y),axis = 1)
ii

array([[ 3,  1,  1,  5,  2,  1],
       [15,  3,  6,  4, 23,  1]])

In [ ]:
np.vstack((x,y))

array([[ 3,  1,  1],
       [15,  3,  6],
       [ 5,  2,  1],
       [ 4, 23,  1]])

In [ ]:
np.hstack((x,y))

array([[ 3,  1,  1,  5,  2,  1],
       [15,  3,  6,  4, 23,  1]])

In [ ]:
np.split(x,2)

[array([[3, 1, 1]]), array([[15,  3,  6]])]

In [ ]:
x

array([[ 3,  1,  1],
       [15,  3,  6]])

In [ ]:
np.array_split(x, 6)

[array([[3, 1, 1]]),
 array([[15,  3,  6]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
np.hsplit(x, 3)

[array([[ 3],
        [15]]),
 array([[1],
        [3]]),
 array([[1],
        [6]])]

In [ ]:
x.flatten()

array([ 3,  1,  1, 15,  3,  6])

In [ ]:
x.T

array([[ 3, 15],
       [ 1,  3],
       [ 1,  6]])

OR

In [ ]:
x.transpose()

array([[ 3, 15],
       [ 1,  3],
       [ 1,  6]])

In [ ]:
x.cumsum()

array([ 3,  4,  5, 20, 23, 29])

In [ ]:
#Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.

#Sample Solution:

# Python Code:


# Creating a 3x3 NumPy array filled with ones
x = np.ones((3, 3))

# Printing a message indicating the checkerboard pattern
print("Checkerboard pattern:")

# Creating an 8x8 NumPy array filled with zeros and setting alternate elements to 1 to create a checkerboard pattern
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1  # Setting alternate rows starting from the second row with alternate columns to 1
x[::2, 1::2] = 1  # Setting alternate rows starting from the first row with alternate columns to 1

# Printing the resulting checkerboard pattern array
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the matrix with the checkerboard pattern
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
with open('/content/Data.Json2.txt') as file:
  print(file.read())

{
"1" : {"Name" : "Augustus", "Age" : 53},
"2" : {"Name" : "Jacob", "Age" : 34}
}


YOu have two ways to import a file
eigther by copy path or the name of the file

In [ ]:
with open('my_file.txt') as file:
  print(file.read())

Mr Jacob always uses so to teach
He dresses appropiately to class
He is a savage
He is caring
Ikenna is going to collect because he uses my name, to make unnecessary sentence



In [ ]:
import numpy as np
data = np.genfromtxt('data.CSV', delimiter=',',dtype = str)

In [ ]:
data

array([['id', 'name', 'age'],
       ['1', 'Jacob', '12'],
       ['2', 'Susan', '34'],
       ['3', 'Augustus', '53']], dtype='<U8')