In [1]:
import numpy as np

# Create a 2x3 matrix with random numerical data
matrix = np.random.rand(2, 3)
print("Matrix:")
print(matrix)

# Identify the data type of the matrix
data_type = matrix.dtype
print("Data type of the matrix:", data_type)

# Calculate mean, mode, and median
mean = np.mean(matrix)
mode = np.median(matrix)
median = np.median(matrix)
print("Mean of the matrix:", mean)
print("Mode of the matrix:", mode)
print("Median of the matrix:", median)

# Basic matrix operations
# Addition
matrix_addition = matrix + matrix
print("Matrix Addition:")
print(matrix_addition)

# Subtraction
matrix_subtraction = matrix - matrix
print("Matrix Subtraction:")
print(matrix_subtraction)

# Transpose
matrix_transpose = np.transpose(matrix)
print("Matrix Transpose:")
print(matrix_transpose)

# Scalar Multiplication
scalar = 2
matrix_scalar_multiplication = scalar * matrix
print("Scalar Multiplication:")
print(matrix_scalar_multiplication)

Matrix:
[[0.65183995 0.85395488 0.74377935]
 [0.67564051 0.89756349 0.49986593]]
Data type of the matrix: float64
Mean of the matrix: 0.7204406839437022
Mode of the matrix: 0.7097099299486369
Median of the matrix: 0.7097099299486369
Matrix Addition:
[[1.30367989 1.70790976 1.4875587 ]
 [1.35128102 1.79512699 0.99973185]]
Matrix Subtraction:
[[0. 0. 0.]
 [0. 0. 0.]]
Matrix Transpose:
[[0.65183995 0.67564051]
 [0.85395488 0.89756349]
 [0.74377935 0.49986593]]
Scalar Multiplication:
[[1.30367989 1.70790976 1.4875587 ]
 [1.35128102 1.79512699 0.99973185]]
