In [23]:
X = [20,15,40,60,10,30,50]
y = [2,3,5,7,1,3,6]

In [24]:
import plotly.express as px

In [25]:
px.scatter(x=X,y=Y,width=900,height = 600)

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import metrics

In [27]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
print('xtrain shape: ',len(xtrain))
print('xtest shape: ',len(xtest))
print('ytrain shape: ',len(ytrain))
print('ytest shape: ',len(ytest))

xtrain shape:  5
xtest shape:  2
ytrain shape:  5
ytest shape:  2


In [29]:
model=LinearRegression()

In [30]:
# xtrain=np.array(xtrain).reshape(-1,1)
# xtest=np.array(xtest).reshape(-1,1)

In [31]:
xtrain=np.array(xtrain)

In [32]:
model.fit(xtrain.reshape(-1,1),ytrain)

LinearRegression()

In [42]:
ytest,predicted

([6, 5], array([5.71835443, 4.62341772]))

In [33]:
xtest

[50, 40]

In [34]:
model.predict(xtest.reshape(-1,1))

AttributeError: 'list' object has no attribute 'reshape'

In [35]:
import numpy as np

# Convert xtest to a NumPy array before reshaping
xtest_array = np.array(xtest)
model.predict(xtest_array.reshape(-1,1))

array([5.71835443, 4.62341772])

In [38]:
predicted = model.predict(xtest_array.reshape(-1,1)) # Store the result of the prediction

In [39]:
mean_squared_error(ytest,predicted)

0.11056921967633387

In [37]:
import numpy as np

# Convert xtest to a NumPy array before reshaping
xtest_array = np.array(xtest)
predicted = model.predict(xtest_array.reshape(-1,1)) # Store the result of the prediction

mean_squared_error(ytest,predicted)

0.11056921967633387

In [40]:
# slop
model.coef_


array([0.10949367])

In [41]:
model.intercept_

0.24367088607594933

In [46]:
pred = 0.109 * np.array(X) + 0.244

In [47]:
pred

array([2.424, 1.879, 4.604, 6.784, 1.334, 3.514, 5.694])

In [ ]:
px.scatter(x=X,y=Y[y